development:
  adapter: postgresql
  encoding: unicode
  database: map-project_development
  pool: 5
  username: map-project
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: map-project_test
  pool: 5
  username: map-project
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: map-project_production
  pool: 5
  username: iwantmap
  password: 1234
