development:
  adapter: postgresql
  encoding: unicode
  database: map-project_development
  pool: 5
  username: map-project
  password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: map-project_test
  pool: 5
  username: map-project
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: map-project_production
  pool: 5
  username: iwantmap
  password: 1234
